ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.self_destruct_trap]
path = "out/SelfDestructTrap.sol/SelfDestructTrap.json"
response_contract = "0x0000000000000000000000000000000000000000" # To be replaced with deployed ResponseProtocol address
response_function = "rescue(address,address)"
cooldown_period_blocks = 10
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = []

# Probes define which contracts the Drosera network will watch.
# The trap logic then filters these events.
[trap_probes]

[trap_probes.mainnet_probe]
chain_id = 1 # Ethereum Mainnet
# Placeholder address for a contract to monitor.
# The owner must call addContract() on the deployed trap with this address.
target_contracts = ["0x0000000000000000000000000000000000000000"]